### ISSUE TITLE
Need the comma after the quoted title in Greek

### ISSUE THREAD

**Issue by jokogr** [josephwright/biblatex-ieee#20]
Hello,

I am using biblatex-ieee for writing my thesis in Greek and have references appearing like this

```
[63] P. R. Wilson, M. S. Johnstone, M. Neely και D. Boles, «Dynamic Storage Allocation: A Survey and Critical Review,» στο IWMM, 1995, σσ. 1–116.
```

I have the impression that in Greek it is more preferred to have the comma after the quotes, e.g., `«Dynamic Storage Allocation: A Survey and Critical Review»,`. Is it possible to do so?

**Comment by josephwright** [comment]
The position of punctuation here is a 'locale typographic tradition' thing rather than one related to language _per se_. It's also not hard-coded into the style: `csquotes` is used for quoting and as-standard follows typical US typography. Using
```
\usepackage[greek]{babel}
\usepackage{csquotes}
```
should alter the outcome and give you what you are after.

**Comment by jokogr** [comment]
Many thanks for the prompt reply!

I have already been using *polyglossia* and *csquotes* and this is probably why the quotation marks are `«` and `»`. I will post an issue at the *csquotes* repository, then.
